#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term browser obsidian mathematica waveforms misc mischief

# Start polybar status bar
~/.config/polybar/launch.sh

bspc config focus_follows_pointer true
bspc config border_width 1
bspc config window_gap 4
bspc config focused_border_color "#3c3836" 
bspc config normal_border_color "#1d2021"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 0
bspc config right_padding 2
bspc config bottom_padding 2
bspc config left_padding 2


## Window rules
# remove all rules first
bspc rule -r *:*
#1 > terminal
bspc rule -a kitty desktop='^1' follow=on focus=on
#2 > web
bspc rule -a firefox-developer-edition desktop='^2' follow=on focus=on
bspc rule -a obsidian desktop='^3' follow=on focus=on
#3 > file
#bspc rule -a Thunar desktop='^4' follow=on focus=on
#bspc rule -a Dolphin desktop='^5' follow=on focus=on
#bspc rule -a Nautilus desktop='^6' follow=on focus=on
#bspc rule -a File-roller desktop='^7' follow=on focus=on
